version: '3.9'
services:
  db:  
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ../web-app/backend
    ports:
      - "3001:3001"
    env_file: ../infra/.env
    depends_on:
      - db

  bot:
    build: ../python-bot
    env_file: ../infra/.env
    restart: always
    depends_on:
      - db
    command: [ "sh", "-c", "sleep 5 && python vachanamrut_bot.py" ]

  frontend:
    build: ../web-app/frontend
    ports:
      - "3000:80"
    env_file: ../infra/.env
    depends_on:
      - backend

volumes:
  postgres_data:
